spring:
  redis:
    host: 39.98.216.77
    port: 6379
  cloud:
    gateway:
      globalcors: #全局跨域配置
        cors-configurations:
          '[/**]':
            allowCredentials: false  # sessionid 多次访问一致
            allowedHeaders: '*' # 允许任何头
            allowedMethods: '*' # 允许任何方法(post、get等)
            allowedOrigins: '*' # 允许任何域名使用
            add-to-simple-url-handler-mapping: true   # 允许来自所有域名(allowedOrigins)的所有请求方式(allowedMethods)发出CORS请求
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          lower-case-service-id: true #使用小写服务名 默认是大写
      routes:
        # 系统
        - id: fabric-admin
          uri: lb://fabric-admin
          predicates:
            - Path=/system/**,/monitor/**,/tool/**,/traces/**


logging:
  level:
    org.springframework.cloud.gateway: debug


